window.gameTranslations = {
  vi: {
    game_title: 'Vịt Con 3D Háu Ăn 🐥',
    player_label: '🟢 Người chơi:',
    guest_label: '👤 Khách',
    login_link: 'Đăng nhập',
    guest_suffix: 'để lưu tên',
    score_label: 'Điểm Số',
    time_label: 'Thời Gian',
    explore_label: 'Khám Phá',
    chunk_label: 'Tọa Độ Chunk',
    leaderboard_btn: '🏆 BẢNG XẾP HẠNG',
    view_btn: '👀 Chế độ 1st Person',
    view_1st: '👀 Chế độ 1st Person',
    view_3rd: '🔭 Chế độ 3rd Person',
    table_rank: 'Hạng',
    table_player: 'Tên Người Chơi',
    table_score: 'Điểm Số',
    no_rank_data: 'Chưa có dữ liệu xếp hạng',
    controls_title: '🗺️ Bản Đồ Vô Tận & Đồ Họa 3D Cao Cấp:',
    controls_text: 'Dùng',
    controls_or: 'hoặc',
    controls_desc: 'điều khiển Vịt (Nhấn V đổi Góc Nhìn 1st/3rd Person)',
    start_title: '🐥 CHỌN NHÂN VẬT VỊT & THẾ GIỚI 3D SỐNG ĐỘNG 🗺️',
    start_subtitle: 'Khám phá thế giới 3D đa dạng: Thành phố, Nhà cửa, Đường rẫy tàu hỏa, Bãi biển, Tàu biển, Thác nước & Hồ ao!',
    duck_section_label: '🐥 1. CHỌN CHÚ VỊT 3D CỦA BẠN:',
    duck_golden_name: 'Vịt Vàng Vui Vẻ',
    duck_golden_desc: 'Vịt truyền thống rực rỡ',
    duck_cool_name: 'Vịt Cool Boy',
    duck_cool_desc: 'Kính râm ngầu mạ vàng',
    duck_king_name: 'Vịt Hoàng Gia',
    duck_king_desc: 'Vương miện quyền lực',
    duck_fairy_name: 'Vịt Hồng Kẹo Ngọt',
    duck_fairy_desc: 'Sắc hồng ngọt ngào',
    duck_ninja_name: 'Vịt Ninja Đen',
    duck_ninja_desc: 'Băng trán & thân huyền bí',
    map_section_label: '🗺️ 2. CHỌN THẾ GIỚI BẢN ĐỒ 3D (DYNAMIC CHUNK LOADING):',
    map_park_name: 'Đô Thị & Công Viên Xanh',
    map_park_desc: 'Thành phố, Tàu biển, Tàu hỏa & Hồ ao',
    map_volcano_name: 'Đảo Núi Lửa & Dung Nham',
    map_volcano_desc: 'Dòng Dung Nham & Tàu chiến',
    map_snow_name: 'Vương Quốc Băng & Tuyết',
    map_snow_desc: 'Tuyết trắng, Sông băng & Tàu phá băng',
    map_galaxy_name: 'Đêm Ngân Hà Cyberpunk',
    map_galaxy_desc: 'Thành phố Cyber, Tàu vũ trụ & Pha lê',
    time_section_label: '⏱️ 3. CHỌN THỜI GIAN CHƠI:',
    time_60_name: '60 Giây',
    time_60_desc: 'Chớp nhoáng nhanh',
    time_180_name: '3 Phút',
    time_180_desc: 'Vừa đủ khám phá',
    time_300_name: '5 Phút',
    time_300_desc: 'Phiêu lưu cơ bản',
    time_5400_name: '90 Phút',
    time_5400_desc: 'Khám phá vô tận!',
    start_game_btn: '🚀 BẮT ĐẦU VÀO GAME NGAY',
    leaderboard_title: '🏆 BẢNG XẾP HẠNG TOP CAO THỦ',
    leaderboard_desc: 'Danh sách 10 người chơi ghi điểm cao nhất trong Game Vịt 3D:',
    leaderboard_close: 'ĐÓNG BẢNG',
    end_title: '🎉 HOÀN THÀNH CHUYẾN ĐI!',
    display_name_label: 'Tên hiển thị:',
    voucher_label: '🎟️ Mã Giảm Giá 20%:',
    restart_btn: '🔄 ĐỔI BẢN ĐỒ / VỊT KÍCH THÍCH',
    view_leaderboard_btn: '🏆 XEM BẢNG HẠNG'
  },
  en: {
    game_title: 'Hungry 3D Duck 🐥',
    player_label: '🟢 Player:',
    guest_label: '👤 Guest',
    login_link: 'Login',
    guest_suffix: 'to save name',
    score_label: 'Score',
    time_label: 'Time',
    explore_label: 'Explore',
    chunk_label: 'Chunk Coord',
    leaderboard_btn: '🏆 LEADERBOARD',
    view_btn: '👀 1st Person Mode',
    view_1st: '👀 1st Person Mode',
    view_3rd: '🔭 3rd Person Mode',
    table_rank: 'Rank',
    table_player: 'Player Name',
    table_score: 'Score',
    no_rank_data: 'No leaderboards yet',
    controls_title: '🗺️ Endless 3D World & Graphics:',
    controls_text: 'Use',
    controls_or: 'or',
    controls_desc: 'to move Duck (Press V to toggle 1st/3rd Person)',
    start_title: '🐥 CHOOSE YOUR DUCK & 3D WORLD 🗺️',
    start_subtitle: 'Explore rich 3D environments: City Skyscrapers, Trains, Sea Ships, Beaches & Lakes!',
    duck_section_label: '🐥 1. CHOOSE YOUR DUCK:',
    duck_golden_name: 'Happy Golden Duck',
    duck_golden_desc: 'Classic bright duck',
    duck_cool_name: 'Cool Boy Duck',
    duck_cool_desc: 'Sunglasses and gold trim',
    duck_king_name: 'Royal Duck',
    duck_king_desc: 'Power crown',
    duck_fairy_name: 'Sweet Pink Duck',
    duck_fairy_desc: 'Pink and sweet mood',
    duck_ninja_name: 'Black Ninja Duck',
    duck_ninja_desc: 'Mystic mask and stealth',
    map_section_label: '🗺️ 2. CHOOSE 3D WORLD:',
    map_park_name: 'City & Green Park',
    map_park_desc: 'City, Ships, Trains & Lakes',
    map_volcano_name: 'Volcano & Lava Island',
    map_volcano_desc: 'Hot lava & Battleships',
    map_snow_name: 'Snow Kingdom',
    map_snow_desc: 'White snow & Icebreakers',
    map_galaxy_name: 'Cyberpunk Night',
    map_galaxy_desc: 'Neon City & Starships',
    time_section_label: '⏱️ 3. CHOOSE PLAY TIME:',
    time_60_name: '60 Seconds',
    time_60_desc: 'Quick sprint',
    time_180_name: '3 Minutes',
    time_180_desc: 'Balanced exploration',
    time_300_name: '5 Minutes',
    time_300_desc: 'Basic adventure',
    time_5400_name: '90 Minutes',
    time_5400_desc: 'Endless exploration!',
    start_game_btn: '🚀 START GAME NOW',
    leaderboard_title: '🏆 TOP PLAYERS LEADERBOARD',
    leaderboard_desc: 'Top 10 players with highest scores:',
    leaderboard_close: 'CLOSE',
    end_title: '🎉 JOURNEY COMPLETED!',
    display_name_label: 'Display name:',
    voucher_label: '🎟️ 20% Discount Code:',
    restart_btn: '🔄 CHANGE MAP / DUCK',
    view_leaderboard_btn: '🏆 VIEW LEADERBOARD'
  }
};
